hooks:
  pre-commit: "lint-staged"
  # Do not run commitizen on CI
  # see: https://typicode.github.io/husky/#/?id=disable-hooks-in-ci
  prepare-commit-msg: |
    [ -z "$CI" ] && exec < /dev/tty && npx git-cz --hook || true
