name: GitHub Actions
on:
  push:
    branches:
      - master
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - "**"
    tags-ignore:
      - "**"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install Dependencies
        run: npm ci
      - run: npm run test:lint
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 10.14.2
          - 10.x
          - 12.0.0
          - 12.x
          - 14.0.0
          - 14.x
    steps:
      - uses: actions/checkout@v2
      - name: Git Setting
        run: |
          git config --global user.email foo@example.com
          git config --global user.name  hoge
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - run: npm run test:unit-test
  docs_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch all commits to get the details of the committed tags
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install Dependencies
        run: npm ci
      - run: npm run test:readme
  complete:
    name: GitHub Actions / Complete
    needs: [lint, unit_test, docs_test]
    runs-on: ubuntu-latest
    steps:
      - name: void
        run: ""
